name: FTP Deploy

on:
  push:
    branches:
      - main # 주의: 만약 본인의 기본 브랜치 이름이 master라면 master로 바꿔주세요.

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 최신 코드 가져오기
        uses: actions/checkout@v4

      - name: 📂 FTP 서버로 파일 전송하기
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: www/
          # 위 줄의 맨 앞 '#'을 지우면 서버의 특정 폴더 안에만 파일이 올라가게 할 수 있습니다. (예: www, html 등)